# Generated by Django 4.2.9 on 2024-04-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_verification_token_user_email_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
