# Generated by Django 4.2.9 on 2024-04-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_verification_token"),
    ]

    operations = [
        migrations.RemoveField(model_name="medical", name="medicine",),
    ]
