# Generated by Django 4.2.9 on 2024-04-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_medical_medicine"),
    ]

    operations = [
        migrations.AddField(
            model_name="medical",
            name="medicine",
            field=models.CharField(default="No medication prescribed", max_length=200),
            preserve_default=False,
        ),
    ]
