# Generated by Django 4.2.9 on 2024-05-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_profile_avatar_alter_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medical",
            name="s10",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medical",
            name="s6",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medical",
            name="s7",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medical",
            name="s8",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medical",
            name="s9",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
