# Generated by Django 4.2.9 on 2024-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_medical_s10_alter_medical_s6_alter_medical_s7_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medical",
            name="s1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="medical",
            name="s2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="medical",
            name="s3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="medical",
            name="s4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="medical",
            name="s5",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
